# Generated by Django 3.2.6 on 2021-08-30 09:56

from django.db import migrations, models
import summarizer.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summarizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('url', 'URL'), ('video_file', 'Video File'), ('audio_file', 'Audio File'), ('text_file', 'Text File')], default='video_file', max_length=20)),
                ('source_data', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=summarizer.utils.file_uploaded_path)),
                ('summerized_data', models.TextField()),
                ('file_meta_data', models.JSONField(default=dict)),
            ],
        ),
    ]
